import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import LeaseAdminPreview from "./LeaseAdminPreview";
afterEach(cleanup);
const navigation = () => within(screen.getByRole("navigation"));
const openDrivers = () => {
  fireEvent.click(navigation().getByRole("button", { name: "ドライバー" }));
  fireEvent.click(navigation().getByRole("link", { name: "ドライバー一覧" }));
};
const click = (name: string) => fireEvent.click(screen.getByRole("button", { name }));
const choose = (name: string, option: string) => { click(name); click(option); };

describe("管理プレビューの画面間連携", () => {
  it("月額同士の貸し借りで給油なしでも貸出側への駐車案内を保存する", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("試すサンプル"); click("月額同士の貸し借り"); click("切り替える");
    click("大阪 480 り 1201を配車");
    expect(screen.getByText(/利用者は月額リース ¥38,000/)).toBeTruthy();
    expect(screen.queryByText(/利用者は通常日額/)).toBeNull();
    choose("受取場所", "吹田車庫");
    fireEvent.input(screen.getByLabelText("受取時刻"), { target: { value: "06:30" } });
    click("通知文を見る");
    expect(screen.getByText(/佐藤 翔太さん.*06:30までに 吹田車庫 に駐車してください/)).toBeTruthy();
    expect(screen.getByText(/田中 美咲さん.*受取：吹田車庫（06:30）/)).toBeTruthy();
    expect(screen.queryByText(/貸出前の給油：/)).toBeNull();
    click("確認して配車"); click("大阪 480 り 1201を配車");
    expect((screen.getByLabelText("受取時刻") as HTMLInputElement).value).toBe("06:30");
    expect(screen.getByRole("button", { name: "貸し出す人" }).textContent).toContain("佐藤 翔太");
    click("キャンセル");
    expect(screen.getByText(/¥38,000 \/ 月・普段使う車両 大阪 480 れ 2345/)).toBeTruthy();
  });
  it("整備中の車両から当日だけ代車へ変更できる", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("試すサンプル"); click("整備中の代車"); click("切り替える");
    click("大阪 480 り 5678を配車");
    expect(screen.getByText("使用車両：大阪 480 り 5678")).toBeTruthy();
    expect(screen.getByText(/¥35,000 \/ 月・普段使う車両 大阪 480 り 1201/)).toBeTruthy();
    expect((screen.getByRole("button", { name: "大阪 480 り 1201を配車" }) as HTMLButtonElement).disabled).toBe(true);
    click("閉じる"); click("佐藤 翔太 2026-09-09 のシフトを編集");
    expect(screen.getByText("使用車両：大阪 480 り 1201")).toBeTruthy();
  });
  it("月途中の紐付け変更を保存し、再表示で以前の車両も履歴に残す", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("試すサンプル"); click("月途中の紐付け変更"); click("切り替える");
    choose("普段使う車両", "大阪 480 れ 6789を選択");
    click("ドライバー情報を保存");
    fireEvent.click(screen.getAllByRole("button", { name: "佐藤 翔太のラベル・契約を編集" })[0]);
    expect(screen.getByRole("button", { name: "普段使う車両" }).textContent).toContain("6789");
    click("保存済みの紐付け履歴");
    const history = within(screen.getByRole("list", { name: "紐付け履歴" }));
    expect(history.getByText("2026-08-31 から 2026-09-16 の変更前まで")).toBeTruthy();
    expect(history.getByText("2026-09-16 から")).toBeTruthy();
    expect(history.getByText("大阪 480 り 1201")).toBeTruthy();
    expect(history.getByText("大阪 480 れ 6789")).toBeTruthy();
  });
  it("配車の入力を残して場所を登録でき、登録内容と選択を通知へ反映する", () => {
    render(<LeaseAdminPreview />);
    click("高橋 健太 2026-09-07 のシフトを編集"); click("大阪 480 り 1201を配車");
    choose("返却場所", "吹田車庫");
    fireEvent.click(screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }));
    choose("給油の依頼先", "佐藤 翔太 貸し出す人");
    click("駐車場所を編集");
    expect((screen.getByRole("button", { name: "吹田車庫を削除" }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole("textbox", { name: "駐車場所の名前" }), { target: { value: "箕面車庫" } });
    fireEvent.change(screen.getByRole("textbox", { name: "目印" }), { target: { value: "北側入口" } });
    click("駐車場所を追加"); click("閉じる");
    expect(screen.getByRole("button", { name: "返却場所" }).textContent).toContain("吹田車庫");
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("佐藤 翔太");
    click("キャンセル");
    fireEvent.click(within(screen.getByRole("dialog", { name: "変更を破棄しますか？" })).getByRole("button", { name: "キャンセル" }));
    choose("受取場所", "箕面車庫 北側入口");
    click("確認して配車"); click("大阪 480 り 1201を配車"); click("通知文を見る");
    expect(screen.getByText(/受取：箕面車庫（北側入口）（07:00）.*返却：20:00までに 吹田車庫/)).toBeTruthy();
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("佐藤 翔太");
  });
  it("場所だけの未保存入力を破棄しても配車の下書きは残る", () => {
    render(<LeaseAdminPreview />);
    click("高橋 健太 2026-09-07 のシフトを編集"); click("大阪 480 り 1201を配車");
    choose("返却場所", "吹田車庫"); click("駐車場所を編集");
    fireEvent.change(screen.getByRole("textbox", { name: "駐車場所の名前" }), { target: { value: "未保存の車庫" } });
    click("閉じる");
    fireEvent.click(within(screen.getByRole("dialog", { name: "駐車場所の入力を破棄しますか？" })).getByRole("button", { name: "キャンセル" }));
    expect((screen.getByRole("textbox", { name: "駐車場所の名前" }) as HTMLInputElement).value).toBe("未保存の車庫");
    click("閉じる"); click("破棄する");
    expect(screen.getByRole("button", { name: "返却場所" }).textContent).toContain("吹田車庫");
    click("駐車場所を編集");
    expect(screen.queryByText("未保存の車庫")).toBeNull();
    click("閉じる"); click("キャンセル");
    expect(screen.getByRole("dialog", { name: "変更を破棄しますか？" })).toBeTruthy();
  });
  it("事前登録の場所を編集・削除でき、使用中は保護して通知の表示を更新する", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("駐車場所");
    expect((screen.getByRole("button", { name: "豊中車庫を削除" }) as HTMLButtonElement).disabled).toBe(true);
    click("豊中車庫を編集");
    fireEvent.change(screen.getByRole("textbox", { name: "駐車場所の名前" }), { target: { value: "豊中第1車庫" } });
    fireEvent.change(screen.getByRole("textbox", { name: "目印" }), { target: { value: "区画A" } });
    click("変更を保存"); click("新大阪車庫を削除"); click("削除する");
    expect(screen.queryByRole("button", { name: "新大阪車庫を編集" })).toBeNull();
    click("閉じる");
    click("高橋 健太 2026-09-02 のシフトを編集"); click("大阪 480 り 1201を配車"); click("通知文を見る");
    expect(screen.getByText(/受取：豊中第1車庫（区画A）/)).toBeTruthy();
  });
  it("未登録の場合は配車を止め、同じ画面で登録・選択してから確定できる", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("試すサンプル"); click("駐車場所が未設定"); click("切り替える");
    click("大阪 480 り 1201を配車"); click("確認して配車");
    expect(screen.getByRole("alert").textContent).toContain("登録済みの駐車場所");
    click("駐車場所を編集");
    expect(screen.getByText("駐車場所が未登録です。上の欄から追加してください。")).toBeTruthy();
    fireEvent.change(screen.getByRole("textbox", { name: "駐車場所の名前" }), { target: { value: "臨時車庫" } });
    click("駐車場所を追加"); click("閉じる");
    expect(screen.getByRole("button", { name: "受取場所" }).textContent).toContain("駐車場所を選択");
    choose("受取場所", "臨時車庫"); choose("返却場所", "臨時車庫");
    click("確認して配車");
    expect(screen.getByText("使用車両：大阪 480 り 1201")).toBeTruthy();
  });
  it("複数ラベルを編集してシフトへ反映できる", () => {
    render(<LeaseAdminPreview />);
    openDrivers();
    fireEvent.click(screen.getAllByRole("button", { name: "小林 悠斗のラベル・契約を編集" })[0]);
    fireEvent.click(screen.getByRole("checkbox", { name: "Amazon" }));
    fireEvent.click(screen.getByRole("checkbox", { name: "豊中" }));
    fireEvent.click(screen.getByRole("button", { name: "ドライバー情報を保存" }));
    fireEvent.click(navigation().getByRole("link", { name: "シフト" }));
    fireEvent.click(screen.getByRole("button", { name: "Amazon" }));
    expect(screen.getByText("6人 / 全9人")).toBeTruthy();
  });
  it("未保存の編集を残したまま画面移動を取り消せる", () => {
    render(<LeaseAdminPreview />);
    openDrivers();
    fireEvent.click(screen.getAllByRole("button", { name: "佐藤 翔太のラベル・契約を編集" })[0]);
    fireEvent.change(screen.getByRole("spinbutton", { name: "月額料金" }), { target: { value: "39000" } });
    fireEvent.click(navigation().getByRole("link", { name: "シフト" }));
    const dialog = screen.getByRole("dialog", { name: "変更を破棄しますか？" });
    fireEvent.click(within(dialog).getByRole("button", { name: "キャンセル" }));
    expect((screen.getByRole("spinbutton", { name: "月額料金" }) as HTMLInputElement).value).toBe("39000");
  });
  it("ラベル名の変更がドライバー一覧へ反映される", () => {
    render(<LeaseAdminPreview />);
    openDrivers();
    click("ラベルを編集");
    fireEvent.click(screen.getByRole("button", { name: "豊中の名前を変更" }));
    fireEvent.change(screen.getByRole("textbox", { name: "ラベル名" }), { target: { value: "豊中エリア" } });
    fireEvent.click(screen.getByRole("button", { name: "変更を保存" }));
    click("閉じる");
    expect(within(screen.getByRole("table")).getAllByText("豊中エリア")).toHaveLength(4);
  });
  it("配車セルから月額車を選び、確認ひとつで一時利用を反映する", () => {
    render(<LeaseAdminPreview />);
    click("後半（16日〜）");
    click("高橋 健太 2026-09-22 のシフトを編集");
    click("大阪 480 り 1201を配車");
    const confirmation = within(screen.getByRole("dialog", { name: "月額リース車両の配車" }));
    expect(confirmation.getByText("2026/09/22")).toBeTruthy();
    expect(confirmation.getByText("高橋 健太さんに配車")).toBeTruthy();
    expect(confirmation.getByText(/佐藤 翔太さんから車両を借ります/)).toBeTruthy();
    expect(confirmation.getByText(/月額 ¥35,000は据え置き/)).toBeTruthy();
    expect(confirmation.queryByRole("button", { name: "借り手" })).toBeNull();
    expect(confirmation.queryByRole("button", { name: "貸出日" })).toBeNull();
    click("確認して配車");
    const editor = within(screen.getByRole("dialog", { name: "9/22（火）　高橋 健太" }));
    expect(editor.getByText("使用車両：大阪 480 り 1201")).toBeTruthy();
    expect(editor.getByRole("button", { name: "大阪 480 り 1201を配車" }).getAttribute("aria-pressed")).toBe("true");
    click("閉じる");
    expect(screen.getByRole("button", { name: "佐藤 翔太 2026-09-22 のシフトを編集" }).textContent).toContain("車両を貸出");
    expect(screen.getByRole("button", { name: "高橋 健太 2026-09-22 のシフトを編集" }).textContent).toContain("一時借用");
  });
  it("日額から月額へ切り替えた契約と車両をシフトで確認できる", () => {
    render(<LeaseAdminPreview />);
    click("プレビュー操作"); click("試すサンプル"); click("日額から月額へ"); click("切り替える");
    choose("リース区分", "月額リース");
    choose("普段使う車両", "大阪 480 り 5678を選択");
    click("保存してシフトを確認");
    const editor = within(screen.getByRole("dialog", { name: "9/7（月）　伊藤 彩" }));
    expect(editor.getByText("月額リース")).toBeTruthy();
    expect(editor.getByText(/¥35,000 \/ 月・普段使う車両/)).toBeTruthy();
    expect(editor.getByRole("button", { name: "大阪 480 り 5678を配車" }).getAttribute("aria-pressed")).toBe("true");
    click("ドライバーの契約設定");
    choose("リース区分", "日額リース");
    click("保存してシフトを確認");
    expect(within(screen.getByRole("dialog")).getByText("日額リース")).toBeTruthy();
    expect(within(screen.getByRole("dialog")).getByText(/通常日額 ¥1,800/)).toBeTruthy();
  });
  it("月額車の確認をキャンセルしても元の配車を保ち、確定後も利用を取り消せる", () => {
    render(<LeaseAdminPreview />);
    click("高橋 健太 2026-09-07 のシフトを編集");
    click("大阪 480 り 1201を配車");
    choose("返却場所", "吹田車庫");
    click("キャンセル");
    const discard = within(screen.getByRole("dialog", { name: "変更を破棄しますか？" }));
    fireEvent.click(discard.getByRole("button", { name: "キャンセル" }));
    expect(screen.getByRole("button", { name: "返却場所" }).textContent).toContain("吹田車庫");
    click("キャンセル"); click("破棄する");
    expect(screen.getByText("使用車両：大阪 480 れ 4567")).toBeTruthy();
    click("大阪 480 り 1201を配車");
    expect(screen.getByRole("button", { name: "返却場所" }).textContent).toContain("豊中車庫");
    click("確認して配車");
    click("大阪 480 り 1201を配車");
    click("一時利用を取り消す"); fireEvent.click(within(screen.getByRole("dialog", { name: "月額車の一時利用を取り消しますか？" })).getByRole("button", { name: "一時利用を取り消す" }));
    expect(screen.getByText("使用車両：大阪 480 れ 4567")).toBeTruthy();
    click("閉じる");
    expect(screen.getByRole("button", { name: "佐藤 翔太 2026-09-07 のシフトを編集" }).textContent).not.toContain("車両を貸出");
    expect(screen.getByRole("button", { name: "高橋 健太 2026-09-07 のシフトを編集" }).textContent).not.toContain("一時借用");
  });
  it("通知を選んだ項目は内容必須とし、選択を外した指示は保存・文面から除く", () => {
    render(<LeaseAdminPreview />);
    click("高橋 健太 2026-09-07 のシフトを編集"); click("大阪 480 り 1201を配車");
    fireEvent.click(screen.getByRole("checkbox", { name: "移動・受け渡しの連絡を加える" }));
    click("確認して配車");
    expect(screen.getByRole("alert").textContent).toContain("通知する移動・受け渡しの内容を入力");
    fireEvent.change(screen.getByRole("textbox", { name: "移動・受け渡しの連絡" }), { target: { value: "鍵を指定ボックスへ" } });
    fireEvent.click(screen.getByRole("checkbox", { name: "移動・受け渡しの連絡を加える" }));
    fireEvent.click(screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }));
    fireEvent.change(screen.getByRole("textbox", { name: "給油の指示" }), { target: { value: " " } });
    click("確認して配車");
    expect(screen.getByRole("alert").textContent).toContain("通知する給油の内容を入力");
    fireEvent.change(screen.getByRole("textbox", { name: "給油の指示" }), { target: { value: "貸出前に満タン給油" } });
    click("確認して配車"); click("大阪 480 り 1201を配車");
    expect((screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }) as HTMLInputElement).checked).toBe(true);
    expect((screen.getByRole("checkbox", { name: "移動・受け渡しの連絡を加える" }) as HTMLInputElement).checked).toBe(false);
    click("通知文を見る");
    expect(screen.getByText(/貸出前の給油：貸出前に満タン給油/)).toBeTruthy();
    expect(screen.queryByText(/連絡：鍵を指定ボックスへ/)).toBeNull();
    click("返却済みにする"); fireEvent.click(within(screen.getByRole("dialog", { name: "返却済みにしますか？" })).getByRole("button", { name: "返却済みにする" })); click("大阪 480 り 1201を配車");
    expect(screen.getByText("返却済み")).toBeTruthy();
    expect(screen.queryByRole("button", { name: "確認して内容を保存" })).toBeNull();
  });
  it("ドライバー一覧でラベルを追加・削除でき、元のシフトへ戻っても削除した絞り込みを残さない", () => {
    render(<LeaseAdminPreview />);
    click("豊中");
    fireEvent.click(screen.getAllByRole("button", { name: "佐藤 翔太の契約設定を開く" })[0]);
    click("編集を閉じる"); click("ラベルを編集");
    fireEvent.change(screen.getByRole("textbox", { name: "ラベル名" }), { target: { value: "Amazon" } });
    click("追加");
    expect(screen.getByRole("alert").textContent).toContain("同じ名前のラベル");
    fireEvent.change(screen.getByRole("textbox", { name: "ラベル名" }), { target: { value: "応援" } });
    click("追加");
    expect(screen.getByRole("button", { name: "応援の名前を変更" })).toBeTruthy();
    click("豊中を削除"); click("削除する"); click("閉じる");
    expect(within(screen.getByRole("table")).queryByText("豊中")).toBeNull();
    click("シフトに戻る");
    expect(screen.getByText("9人 / 全9人")).toBeTruthy();
    expect(screen.queryByRole("button", { name: "豊中" })).toBeNull();
    expect(screen.getByRole("button", { name: "すべて" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByRole("button", { name: "応援" })).toBeTruthy();
  });
  it("給油の依頼先を保存・変更でき、依頼をオフにすると内容と宛先を残さない", () => {
    render(<LeaseAdminPreview />);
    click("高橋 健太 2026-09-07 のシフトを編集"); click("大阪 480 り 1201を配車");
    fireEvent.click(screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }));
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("佐藤 翔太");
    choose("給油の依頼先", "佐藤 翔太 貸し出す人");
    fireEvent.change(screen.getByRole("textbox", { name: "給油の指示" }), { target: { value: "貸出前日までに満タン給油" } });
    click("確認して配車"); click("大阪 480 り 1201を配車");
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("佐藤 翔太");
    click("通知文を見る");
    expect(screen.getByText(/佐藤 翔太さん.*貸出前日までに満タン給油/)).toBeTruthy();
    choose("給油の依頼先", "伊藤 彩");
    click("キャンセル");
    fireEvent.click(within(screen.getByRole("dialog", { name: "変更を破棄しますか？" })).getByRole("button", { name: "キャンセル" }));
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("伊藤 彩");
    click("確認して内容を保存"); click("大阪 480 り 1201を配車");
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("伊藤 彩");
    fireEvent.click(screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }));
    click("確認して内容を保存"); click("大阪 480 り 1201を配車"); click("通知文を見る");
    expect((screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }) as HTMLInputElement).checked).toBe(false);
    expect(screen.queryByRole("button", { name: "給油の依頼先" })).toBeNull();
    expect(screen.queryByText(/貸出前の給油：/)).toBeNull();
    expect(screen.getByText(/返却時の給油：使用分を給油し、満タンで返却してください。/)).toBeTruthy();
    fireEvent.click(screen.getByRole("checkbox", { name: "貸出前の満タン給油を依頼する" }));
    expect(screen.getByRole("button", { name: "給油の依頼先" }).textContent).toContain("佐藤 翔太");
    expect((screen.getByRole("textbox", { name: "給油の指示" }) as HTMLInputElement).value).toBe("貸出前に満タンにして引き渡してください。");
  });
  it("貸出側も希望休を解除して別車両で稼働でき、貸出車両の二重配車は防ぐ", () => {
    render(<LeaseAdminPreview />);
    click("佐藤 翔太 2026-09-02 のシフトを編集");
    click("解除"); click("解除する");
    click("Amazon 豊中を追加");
    expect((screen.getByRole("button", { name: "大阪 480 り 1201を配車" }) as HTMLButtonElement).disabled).toBe(true);
    click("大阪 480 れ 6789を配車");
    expect(screen.getByText("使用車両：大阪 480 れ 6789")).toBeTruthy();
    click("この日の利用内容");
    expect(screen.queryByRole("dialog", { name: "変更を破棄しますか？" })).toBeNull();
    expect(screen.getByRole("dialog", { name: "月額車の利用内容" })).toBeTruthy();
  });
  it("追加・解除を即時反映し、他コースと配車を保ったまま車両もプレートで選べる", () => {
    render(<LeaseAdminPreview />);
    click("伊藤 彩 2026-09-02 のシフトを編集");
    click("ヤマト 北大阪を追加");
    expect(screen.getByRole("button", { name: "Amazon 吹田を解除" })).toBeTruthy();
    expect(screen.getByRole("button", { name: "ヤマト 北大阪を解除" })).toBeTruthy();
    expect(screen.getByText("使用車両：大阪 480 り 5678")).toBeTruthy();
    expect(screen.queryByRole("button", { name: "シフトを保存" })).toBeNull();
    click("Amazon 吹田を解除");
    expect(screen.getByText(/通常日額 ¥1,500/)).toBeTruthy();
    click("閉じる");
    expect(screen.getByRole("button", { name: "伊藤 彩 2026-09-02 のシフトを編集" }).textContent).toContain("北大阪");
    click("伊藤 彩 2026-09-02 のシフトを編集");
    click("車両なし");
    expect(screen.getByText("使用車両：車両なし")).toBeTruthy();
    click("大阪 480 り 5678を配車");
    expect(screen.getByRole("button", { name: "大阪 480 り 5678を配車" }).getAttribute("aria-pressed")).toBe("true");
  });
  it("コース軸から追加しても既存の担当コースを置き換えない", () => {
    render(<LeaseAdminPreview />);
    click("表示"); click("コース軸"); click("ヤマト 北大阪 2026-09-02 の割当を編集");
    click("伊藤 彩をコースに追加");
    expect(screen.getByRole("button", { name: "伊藤 彩をコースから外す" })).toBeTruthy();
    click("閉じる"); click("ドライバー軸");
    const cell = screen.getByRole("button", { name: "伊藤 彩 2026-09-02 のシフトを編集" });
    expect(cell.textContent).toContain("北大阪");
    expect(cell.textContent).toContain("吹田");
  });
  it("ラベルを複数オン・個別オフ・全解除でき、契約・検索と組み合わせられる", () => {
    render(<LeaseAdminPreview />);
    click("Amazon"); click("ヤマト");
    expect(screen.getByText("8人 / 全9人")).toBeTruthy();
    choose("リース区分で絞り込み", "日額リース");
    expect(screen.getByText("3人 / 全9人")).toBeTruthy();
    fireEvent.change(screen.getByRole("textbox", { name: "ドライバーを検索" }), { target: { value: "小林" } });
    expect(screen.getByText(/条件に合うドライバーはいません/)).toBeTruthy();
    click("ラベル未設定");
    expect(screen.getByText("1人 / 全9人")).toBeTruthy();
    fireEvent.change(screen.getByRole("textbox", { name: "ドライバーを検索" }), { target: { value: "" } });
    click("Amazon"); click("ラベル未設定");
    expect(screen.getByText("1人 / 全9人")).toBeTruthy();
    click("ヤマト");
    expect(screen.getByRole("button", { name: "すべて" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByText("4人 / 全9人")).toBeTruthy();
  });
  it("契約設定から戻っても元のシフトの期間・絞り込み・表示項目を保つ", () => {
    render(<LeaseAdminPreview />);
    click("Amazon"); click("豊中"); click("後半（16日〜）");
    click("表示"); click("シフト"); click("集合時刻");
    fireEvent.click(screen.getAllByRole("button", { name: "田中 美咲の契約設定を開く" })[0]);
    click("編集を閉じる"); click("シフトに戻る");
    expect(screen.getByRole("button", { name: "後半（16日〜）" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByRole("button", { name: "Amazon" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByRole("button", { name: "豊中" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByText("6人 / 全9人")).toBeTruthy();
    click("表示");
    const options = within(screen.getByRole("group", { name: "表示する項目" }));
    expect(options.getByRole("button", { name: "シフト" }).getAttribute("aria-pressed")).toBe("false");
    expect(options.getByRole("button", { name: "車両" }).getAttribute("aria-pressed")).toBe("true");
    expect(options.getByRole("button", { name: "集合時刻" }).getAttribute("aria-pressed")).toBe("true");
    const cell = within(screen.getByRole("table")).getByRole("button", { name: "田中 美咲 2026-09-17 のシフトを編集" });
    expect(cell.textContent).toContain("集合 07:30");
    expect(cell.textContent).not.toContain("終日");
    fireEvent.click(options.getByRole("button", { name: "シフト" }));
    expect(cell.textContent).toContain("終日");
  });
  it("日別タブは人数・一覧を切り替え、PCの半月表は全員を保つ", () => {
    render(<LeaseAdminPreview />);
    const tabs = within(screen.getByRole("group", { name: "日別の表示対象" }));
    const list = within(screen.getByRole("region", { name: "日別シフト一覧" }));
    const desktop = within(screen.getByRole("table"));
    expect(tabs.getByRole("button", { name: /^稼働\s*7$/ }).getAttribute("aria-pressed")).toBe("true");
    expect(list.queryByRole("button", { name: "田中 美咲の契約設定を開く" })).toBeNull();
    expect(desktop.getByRole("button", { name: "田中 美咲の契約設定を開く" })).toBeTruthy();
    fireEvent.click(tabs.getByRole("button", { name: /^未割当\s*2$/ }));
    expect(list.getAllByText("希望休")).toHaveLength(2);
    expect(list.queryByRole("button", { name: "佐藤 翔太の契約設定を開く" })).toBeNull();
    fireEvent.change(screen.getByRole("textbox", { name: "ドライバーを検索" }), { target: { value: "佐藤" } });
    expect(tabs.getByRole("button", { name: /^全員\s*1$/ })).toBeTruthy();
    expect(tabs.getByRole("button", { name: /^未割当\s*0$/ }).getAttribute("aria-pressed")).toBe("true");
    expect(list.getByText(/タブを切り替えてください/)).toBeTruthy();
    fireEvent.click(tabs.getByRole("button", { name: /^全員\s*1$/ }));
    expect(list.getByRole("button", { name: "佐藤 翔太の契約設定を開く" })).toBeTruthy();
    click("次の日");
    expect(tabs.getByRole("button", { name: /^未割当\s*1$/ })).toBeTruthy();
    expect(list.getByText("希望休")).toBeTruthy();
  });

  it("車両を隠すと名前の補足情報も畳み、絞り込みを保ったまま個別に戻せる", () => {
    render(<LeaseAdminPreview />);
    click("Amazon");
    fireEvent.click(screen.getByRole("checkbox", { name: "契約区分でまとめる" }));
    click("表示"); click("車両");
    const table = within(screen.getByRole("table"));
    const nameCell = () => within(table.getByRole("button", { name: "佐藤 翔太の契約設定を開く" }).closest("th")!);
    const mobile = within(screen.getByRole("region", { name: "日別シフト一覧" }));
    expect(nameCell().queryByText("Amazon")).toBeNull();
    expect(nameCell().queryByText("月額リース")).toBeNull();
    expect(mobile.queryByText("月額リース")).toBeNull();
    expect(mobile.queryAllByText("Amazon")).toHaveLength(0);
    expect(screen.getByRole("button", { name: "Amazon" }).getAttribute("aria-pressed")).toBe("true");
    expect(screen.getByText("5人 / 全9人")).toBeTruthy();
    expect(table.getByRole("button", { name: "佐藤 翔太 2026-09-01 のシフトを編集" }).textContent).toContain("豊中");
    click("ラベル・契約");
    expect(nameCell().getByText("Amazon")).toBeTruthy();
    expect(nameCell().getByText("月額リース")).toBeTruthy();
    // 明示的に変更した補足表示は、その後の車両表示の切替では上書きしない。
    click("ラベル・契約"); click("車両");
    expect(nameCell().queryByText("月額リース")).toBeNull();
    expect(screen.getByRole("button", { name: "ラベル・契約" }).getAttribute("aria-pressed")).toBe("false");
  });

});
